=== dmn-tck/tck/TestCases/testCases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (x64) (http://www.altova.com) by Bruce Silver (private) -->
<xs:schema xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.omg.org/spec/DMN/20160719/testcase" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="testCaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="decision"/>
			<xs:enumeration value="bkm"/>
			<xs:enumeration value="decisionService"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="testCases">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="testCasesName" type="xs:string" minOccurs="0"/>
				<xs:element name="modelName" type="xs:string" minOccurs="0"/>
				<xs:element name="labels" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="testCase" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="inputNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="valueType">
											<xs:attribute name="name" use="required"/>
											<xs:attribute name="namespace" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="resultNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="expected" type="valueType" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="errorResult" type="xs:boolean" default="false"/>
									<xs:attribute name="name" use="required"/>
									<xs:attribute name="namespace" type="xs:string" use="optional"/>
									<xs:attribute name="type" type="xs:string"/>
									<xs:anyAttribute namespace="##other" processContents="lax"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="extensionElements" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string"/>
						<xs:attribute name="type" type="testCaseType" default="decision"/>
						<xs:attribute name="invocableName" type="xs:string"/> <!-- if type==decisionService, this attribute will point at which DS to invoke. -->
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="namespace" type="xs:string" use="optional"/>
						<xs:anyAttribute namespace="##other" processContents="lax"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string" use="optional"/>
			<xs:anyAttribute namespace="##other" processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="valueType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="value" type="xs:anySimpleType" nillable="true"/>
				<xs:element name="component" nillable="true" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="valueType">
								<xs:attribute name="name" />
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="list" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" type="valueType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="extensionElements" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
</xs:schema>

=== dmn-tck/tck/TestExamples/lending1/lending1-output-001.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../TestCases/testCases.xsd">
	<modelName>lending1.dmn</modelName>
	<testCase id="001">
		<inputNode name="Applicant Data">
			<component name="Monthly">
				<component name="Income">
					<value>6000</value>
				</component>
				<component name="Expenses">
					<value>2000</value>
				</component>
				<component name="Repayments">
					<value>0</value>
				</component>
			</component>
			<component name="Age">
				<value>35</value>
			</component>
			<component name="Existing Customer">
				<value>true</value>
			</component>
			<component name="Marital Status">
				<value>M</value>
			</component>
			<component name="Employment Status">
				<value>EMPLOYED</value>
			</component>
		</inputNode>
		<inputNode name="Requested Product">
			<component name="Product Type">
				<value>STANDARD LOAN</value>
			</component>
			<component name="Amount">
				<value>350000</value>
			</component>
			<component name="Rate">
				<value>0.0395</value>
			</component>
			<component name="Term">
				<value>360</value>
			</component>
		</inputNode>
		<inputNode name="Bureau Data">
			<component name="Credit Score">
				<value>649</value>
			</component>
			<component name="Bankrupt">
				<value>false</value>
			</component>
		</inputNode>
		<resultNode name="Application Risk Score" type="decision">
			<computed>
				<value>90</value>
			</computed>
		</resultNode>
		<resultNode name="Pre-bureau Risk Category" type="decision">
			<computed>
				<value>HIGH</value>
			</computed>
		</resultNode>
		<resultNode name="Bureau Call Type" type="decision">
			<computed>
				<value>FULL</value>
			</computed>
		</resultNode>
		<resultNode name="Post-bureau Risk Category" type="decision">
			<computed>
				<value>LOW</value>
			</computed>
		</resultNode>
		<resultNode name="Required Monthly Installment" type="decision">
			<computed>
				<value>1680.880325608555</value>
			</computed>
		</resultNode>
		<resultNode name="Pre-bureau Affordability" type="decision">
			<computed>
				<value>true</value>
			</computed>
		</resultNode>
		<resultNode name="Eligibility" type="decision">
			<computed>
				<value>ELIGIBLE</value>
			</computed>
		</resultNode>
		<resultNode name="Strategy" type="decision">
			<computed>
				<value>BUREAU</value>
			</computed>
		</resultNode>
		<resultNode name="Post-bureau Affordability" type="decision">
			<computed>
				<value>true</value>
			</computed>
		</resultNode>
		<resultNode name="Routing" type="decision">
			<computed>
				<value>ACCEPT</value>
			</computed>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0007-date-time/0007-date-time-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0007-date-time.dmn</modelName>
	<testCase id="001">
		<inputNode name="dateString">
			<value>2015-12-24</value>
		</inputNode>
		<inputNode name="timeString">
			<value>00:00:01-01:00</value>
		</inputNode>
		<inputNode name="dateTimeString">
			<value>2016-12-24T23:59:00-08:00</value>
		</inputNode>
		<inputNode name="Hours">
			<value>12</value>
		</inputNode>
		<inputNode name="Minutes">
			<value>59</value>
		</inputNode>
		<inputNode name="Seconds">
			<value>01.3</value>
		</inputNode>
		<inputNode name="Timezone">
			<value>-PT1H</value>
		</inputNode>
		<inputNode name="Year">
			<value>1999</value>
		</inputNode>
		<inputNode name="Month">
			<value>11</value>
		</inputNode>
		<inputNode name="Day">
			<value>22</value>
		</inputNode>
		<inputNode name="oneHour">
			<value>PT1H</value>
		</inputNode>
		<inputNode name="durationString">
			<value>P13DT2H14S</value>
		</inputNode>
		<resultNode name="Date-Time" type="decision">
			<expected>
				<value>2016-12-24T23:59:00-08:00</value>
			</expected>
		</resultNode>
		<resultNode name="Date" type="decision">
			<expected>
				<component name="fromString">
					<value>2015-12-24</value>
				</component>
				<component name="fromDateTime">
					<value>2016-12-24</value>
				</component>
				<component name="fromYearMonthDay">
					<value>1999-11-22</value>
				</component>
			</expected>
		</resultNode>
		<resultNode name="Time" type="decision">
			<expected>
				<value>00:00:01-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="Date-Time2" type="decision">
			<expected>
				<value>2015-12-24T00:00:01-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="Time2" type="decision">
			<expected>
				<value>00:00:01-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="Time3" type="decision">
			<expected>
				<value>12:59:01.3-01:00</value>
			</expected>
		</resultNode>
		<resultNode name="dtDuration1" type="decision">
			<expected>
				<value>P13DT2H14S</value>
			</expected>
		</resultNode>
		<resultNode name="dtDuration2" type="decision">
			<expected>
				<value>P367DT6H58M59S</value>
			</expected>
		</resultNode>
		<resultNode name="hoursInDuration" type="decision">
			<expected>
				<value>8814.98305555556</value>
			</expected>
		</resultNode>
		<resultNode name="sumDurations" type="decision">
			<expected>
				<value>P380DT8H59M13S</value>
			</expected>
		</resultNode>
		<resultNode name="ymDuration2" type="decision">
			<expected>
				<value>P1Y0M</value>
			</expected>
		</resultNode>
		<resultNode name="cDay" type="decision">
			<expected>
				<value>24</value>
			</expected>
		</resultNode>
		<resultNode name="cYear" type="decision">
			<expected>
				<value>2015</value>
			</expected>
		</resultNode>
		<resultNode name="cMonth" type="decision">
			<expected>
				<value>12</value>
			</expected>
		</resultNode>
		<resultNode name="cHour" type="decision">
			<expected>
				<value>0</value>
			</expected>
		</resultNode>
		<resultNode name="cMinute" type="decision">
			<expected>
				<value>0</value>
			</expected>
		</resultNode>
		<resultNode name="cSecond" type="decision">
			<expected>
				<value>1</value>
			</expected>
		</resultNode>
		<resultNode name="cTimezone" type="decision">
			<expected>
				<value>-PT1H</value>
			</expected>
		</resultNode>
		<resultNode name="years" type="decision">
			<expected>
				<value>1</value>
			</expected>
		</resultNode>
		<resultNode name="seconds" type="decision">
			<expected>
				<value>14</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0010-concatenate/0010-concatenate-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0010-concatenate.dmn</modelName>
	<testCase>
		<inputNode name="simpleList">
			<list>
				<item>
					<value>a</value>
				</item>
				<item>
					<value>b</value>
				</item>
				<item>
					<value>c</value>
				</item>
			</list>
		</inputNode>
		<inputNode name="nestedList">
			<list>
				<item>
					<list>
						<item>
							<value>w</value>
						</item>
						<item>
							<value>x</value>
						</item>
					</list>
				</item>
				<item>
					<value>y</value>
				</item>
				<item>
					<value>z</value>
				</item>
			</list>
		</inputNode>
		<resultNode name="literalSimpleList">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="literalNestedList">
			<expected>
				<list>
					<item>
						<list>
							<item>
								<value>w</value>
							</item>
							<item>
								<value>x</value>
							</item>
						</list>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="concatenate1">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="concatenate2">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<value>w</value>
							</item>
							<item>
								<value>x</value>
							</item>
						</list>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="concatenate3">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<value>w</value>
							</item>
							<item>
								<value>x</value>
							</item>
						</list>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="concatenate4">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<value>w</value>
							</item>
							<item>
								<value>x</value>
							</item>
						</list>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0004-lending/0004-lending-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0004-lending.dmn</modelName>
	<testCase id="001">
		<inputNode name="ApplicantData" type="inputData">
			<component name="Monthly">
				<component name="Income">
					<value>6000</value>
				</component>
				<component name="Expenses">
					<value>2000</value>
				</component>
				<component name="Repayments">
					<value>0</value>
				</component>
			</component>
			<component name="Age">
				<value>35</value>
			</component>
			<component name="ExistingCustomer">
				<value>true</value>
			</component>
			<component name="MaritalStatus">
				<value>M</value>
			</component>
			<component name="EmploymentStatus">
				<value>EMPLOYED</value>
			</component>
		</inputNode>
		<inputNode name="RequestedProduct" type="inputData">
			<component name="ProductType">
				<value>STANDARD LOAN</value>
			</component>
			<component name="Amount">
				<value>350000</value>
			</component>
			<component name="Rate">
				<value>0.0395</value>
			</component>
			<component name="Term">
				<value>360</value>
			</component>
		</inputNode>
		<inputNode name="BureauData" type="inputData">
			<component name="CreditScore">
				<value>649</value>
			</component>
			<component name="Bankrupt">
				<value>false</value>
			</component>
		</inputNode>
		<inputNode name="SupportingDocuments" type="inputData">
			<value>YES</value>
		</inputNode>
		<inputNode name="Adjudication" type="decision">
			<value>ACCEPT</value>
		</inputNode>
		<resultNode name="ApplicationRiskScore" type="decision">
			<expected>
				<value>130</value>
			</expected>
		</resultNode>
		<resultNode name="Pre-bureauRiskCategory" type="decision">
			<expected>
				<value>LOW</value>
			</expected>
		</resultNode>
		<resultNode name="BureauCallType" type="decision">
			<expected>
				<value>MINI</value>
			</expected>
		</resultNode>
		<resultNode name="Post-bureauRiskCategory" type="decision">
			<expected>
				<value>LOW</value>
			</expected>
		</resultNode>
		<resultNode name="RequiredMonthlyInstallment" type="decision">
			<expected>
				<value>1680.880325608555</value>
			</expected>
		</resultNode>
		<resultNode name="Pre-bureauAffordability" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="Eligibility" type="decision">
			<expected>
				<value>ELIGIBLE</value>
			</expected>
		</resultNode>
		<resultNode name="Strategy" type="decision">
			<expected>
				<value>BUREAU</value>
			</expected>
		</resultNode>
		<resultNode name="Post-bureauAffordability" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="Routing" type="decision">
			<expected>
				<value>ACCEPT</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>
