=== dmn-tck/tck/TestCases/testCases.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (x64) (http://www.altova.com) by Bruce Silver (private) -->
<xs:schema xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.omg.org/spec/DMN/20160719/testcase" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="testCaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="decision"/>
			<xs:enumeration value="bkm"/>
			<xs:enumeration value="decisionService"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="testCases">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="testCasesName" type="xs:string" minOccurs="0"/>
				<xs:element name="modelName" type="xs:string" minOccurs="0"/>
				<xs:element name="labels" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="testCase" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="inputNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="valueType">
											<xs:attribute name="name" use="required"/>
											<xs:attribute name="namespace" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="resultNode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="expected" type="valueType" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="errorResult" type="xs:boolean" default="false"/>
									<xs:attribute name="name" use="required"/>
									<xs:attribute name="namespace" type="xs:string" use="optional"/>
									<xs:attribute name="type" type="xs:string"/>
									<xs:anyAttribute namespace="##other" processContents="lax"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="extensionElements" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string"/>
						<xs:attribute name="type" type="testCaseType" default="decision"/>
						<xs:attribute name="invocableName" type="xs:string"/> <!-- if type==decisionService, this attribute will point at which DS to invoke. -->
						<xs:attribute name="name" type="xs:string"/>
						<xs:attribute name="namespace" type="xs:string" use="optional"/>
						<xs:anyAttribute namespace="##other" processContents="lax"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="namespace" type="xs:string" use="optional"/>
			<xs:anyAttribute namespace="##other" processContents="lax"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="valueType">
		<xs:sequence>
			<xs:choice>
				<xs:element name="value" type="xs:anySimpleType" nillable="true"/>
				<xs:element name="component" nillable="true" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="valueType">
								<xs:attribute name="name" />
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="list" nillable="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" type="valueType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name="extensionElements" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
</xs:schema>

=== dmn-tck/tck/TestCases/compliance-level-3/0009-append-flatten/0009-append-flatten-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0009-append-flatten.dmn</modelName>
    <labels>
        <label>Compliance Level 3</label>
        <label>Literal Expression</label>
        <label>Item Definition</label>
        <label>FEEL List</label>
        <label>FEEL Functions: lists</label>
    </labels>
    <testCase id="001">
		<inputNode name="simpleList">
			<list>
				<item>
					<value>a</value>
				</item>
				<item>
					<value>b</value>
				</item>
				<item>
					<value>c</value>
				</item>
			</list>
		</inputNode>
		<inputNode name="nestedList">
			<list>
				<item>
					<list>
						<item>
							<value>w</value>
						</item>
						<item>
							<value>x</value>
						</item>
					</list>
				</item>
				<item>
					<value>y</value>
				</item>
				<item>
					<value>z</value>
				</item>
			</list>
		</inputNode>
		<resultNode name="literalSimpleList" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="literalNestedList" type="decision">
			<expected>
				<list>
					<item>
						<list>
							<item>
								<value>w</value>
							</item>
							<item>
								<value>x</value>
							</item>
						</list>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="append1" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<value>a</value>
							</item>
							<item>
								<value>b</value>
							</item>
							<item>
								<value>c</value>
							</item>
						</list>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="append2" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<list>
									<item>
										<value>w</value>
									</item>
									<item>
										<value>x</value>
									</item>
								</list>
							</item>
							<item>
								<value>y</value>
							</item>
							<item>
								<value>z</value>
							</item>
						</list>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="append3" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<list>
									<item>
										<value>w</value>
									</item>
									<item>
										<value>x</value>
									</item>
								</list>
							</item>
							<item>
								<value>y</value>
							</item>
							<item>
								<value>z</value>
							</item>
						</list>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="append4" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<list>
							<item>
								<list>
									<item>
										<value>w</value>
									</item>
									<item>
										<value>x</value>
									</item>
								</list>
							</item>
							<item>
								<value>y</value>
							</item>
							<item>
								<value>z</value>
							</item>
						</list>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="flatten1" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="flatten2" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<value>w</value>
					</item>
					<item>
						<value>x</value>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="flatten3" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<value>w</value>
					</item>
					<item>
						<value>x</value>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="flatten4" type="decision">
			<expected>
				<list>
					<item>
						<value>a</value>
					</item>
					<item>
						<value>b</value>
					</item>
					<item>
						<value>c</value>
					</item>
					<item>
						<value>w</value>
					</item>
					<item>
						<value>x</value>
					</item>
					<item>
						<value>y</value>
					</item>
					<item>
						<value>z</value>
					</item>
				</list>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-2/0101-feel-constants/0101-feel-constants-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0101-feel-constants.dmn</modelName>
	<labels>
	    <label>Compliance Level 2</label>
		<label>Literal Expression</label>
	    <label>FEEL Constants</label>
	    <label>Data Type: Number</label>
	</labels>
	<testCase id="001"> 
		<description>Tests FEEL number constants</description>
		<resultNode name="Decision1" type="decision">
			<expected>
				<value>0.872</value>
			</expected>
		</resultNode>
	    <resultNode name="Decision2" type="decision">
	        <expected>
	            <value>-0.872</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision3" type="decision">
	        <expected>
	            <value>0.872</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision4" type="decision">
	        <expected>
	            <value>50</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision5" type="decision">
	        <expected>
	            <value>-50</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision6" type="decision">
	        <expected>
	            <value>50</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision7" type="decision">
	        <expected>
	            <value>125.4321987654</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision8" type="decision">
	        <expected>
	            <value>-125.4321987654</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision9" type="decision">
	        <expected>
	            <value>125.4321987654</value>
	        </expected>
	    </resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0006-join/0006-join-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="dmnexecute61220.xslt"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0006-join.dmn</modelName>
    <labels>
        <label>Compliance Level 3</label>
        <label>Literal Expression</label>
        <label>Item Definition</label>
        <label>FEEL Filter (10.3.2.5)</label>
        <label>FEEL List</label>
        <label>FEEL Relation</label>
    </labels>
    <testCase id="001">
		<inputNode name="EmployeeTable">
			<list>
				<item>
					<component name="id">
						<value>7792</value>
					</component>
					<component name="deptNum">
						<value>10</value>
					</component>
					<component name="name">
						<value>Clark</value>
					</component>
				</item>
				<item>
					<component name="id">
						<value>7934</value>
					</component>
					<component name="deptNum">
						<value>10</value>
					</component>
					<component name="name">
						<value>Miller</value>
					</component>
				</item>
				<item>
					<component name="id">
						<value>7976</value>
					</component>
					<component name="deptNum">
						<value>20</value>
					</component>
					<component name="name">
						<value>Adams</value>
					</component>
				</item>
				<item>
					<component name="id">
						<value>7902</value>
					</component>
					<component name="deptNum">
						<value>20</value>
					</component>
					<component name="name">
						<value>Ford</value>
					</component>
				</item>
				<item>
					<component name="id">
						<value>7900</value>
					</component>
					<component name="deptNum">
						<value>30</value>
					</component>
					<component name="name">
						<value>James</value>
					</component>
				</item>
			</list>
		</inputNode>
		<inputNode name="DeptTable">
			<list>
				<item>
					<component name="number">
						<value>10</value>
					</component>
					<component name="name">
						<value>Sales</value>
					</component>
					<component name="manager">
						<value>Smith</value>
					</component>
				</item>
				<item>
					<component name="number">
						<value>20</value>
					</component>
					<component name="name">
						<value>Finance</value>
					</component>
					<component name="manager">
						<value>Jones</value>
					</component>
				</item>
				<item>
					<component name="number">
						<value>30</value>
					</component>
					<component name="name">
						<value>Engineering</value>
					</component>
					<component name="manager">
						<value>King</value>
					</component>
				</item>
			</list>
		</inputNode>
		<inputNode name="LastName">
			<value>Clark</value>
		</inputNode>
		<resultNode name="Join" type="decision">
			<expected>
				<value>Smith</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0002-string-functions/0002-string-functions-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<modelName>0002-string-functions.dmn</modelName>
    <labels>
        <label>Compliance Level 3</label>
        <label>Literal Expression</label>
        <label>Context</label>
        <label>Item Definition</label>
        <label>FEEL Functions: strings</label>
    </labels>
    <testCase id="001">
		<inputNode name="A">
			<value>banana</value>
		</inputNode>
		<inputNode name="B">
			<value>a</value>
		</inputNode>
		<inputNode name="NumC">
			<value>2</value>
		</inputNode>
		<resultNode name="Basic" type="decision">
			<expected>
				<component name="startsWithX">
					<value>false</value>
				</component>
				<component name="startsWithB">
					<value>false</value>
				</component>
				<component name="endsWithX">
					<value>false</value>
				</component>
				<component name="endsWithB">
					<value>true</value>
				</component>
				<component name="containsX">
					<value>false</value>
				</component>
				<component name="containsB">
					<value>true</value>
				</component>
				<component name="substringC1">
					<value>a</value>
				</component>
				<component name="stringlength">
					<value>6</value>
				</component>
				<component name="uppercase">
					<value>BANANA</value>
				</component>
				<component name="lowercase">
					<value>a</value>
				</component>
				<component name="substringBeforeB">
					<value>b</value>
				</component>
				<component name="substringAfterB">
					<value>nana</value>
				</component>
			</expected>
		</resultNode>
		<resultNode name="Matches" type="decision">
			<expected>
				<value>true</value>
			</expected>
		</resultNode>
		<resultNode name="Replace" type="decision">
			<expected>
				<component name="Aao">
					<value>bonono</value>
				</component>
				<component name="AanplusStarstar">
					<value>b**a</value>
				</component>
				<component name="encloseVowels">
					<value>b[a]n[a]n[a]</value>
				</component>
			</expected>
		</resultNode>
		<resultNode name="Constructor" type="decision">
			<expected>
				<value xsi:type="xsd:string">2</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0018-concat/0018-concat-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0018-concat.dmn</modelName>
	<testCase id="001">
		<inputNode name="a">
			<value>a</value>
		</inputNode>
		<inputNode name="b">
			<value>b</value>
		</inputNode>
		<inputNode name="c">
			<value>c</value>
		</inputNode>
		<resultNode name="concat1" type="decision">
			<expected>
				<value>abc</value>
			</expected>
		</resultNode>
		<resultNode name="concat2" type="decision">
			<expected>
				<value>abc</value>
			</expected>
		</resultNode>
		<resultNode name="concat3" type="decision">
			<expected>
				<value>abc</value>
			</expected>
		</resultNode>
	</testCase>
	<testCase id="002">
		<inputNode name="a">
			<value>1</value>
		</inputNode>
		<inputNode name="b">
			<value>2</value>
		</inputNode>
		<inputNode name="c">
			<value>3</value>
		</inputNode>
		<resultNode name="concat1" type="decision">
			<expected>
				<value>123</value>
			</expected>
		</resultNode>
		<resultNode name="concat2" type="decision">
			<expected>
				<value>123</value>
			</expected>
		</resultNode>
		<resultNode name="concat3" type="decision">
			<expected>
				<value>123</value>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-3/0013-sort/0013-sort-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../testCases.xsd">
	<modelName>0013-sort.dmn</modelName>
	<testCase id="001">
		<inputNode name="listA">
			<list>
				<item>
					<value>3</value>
				</item>
				<item>
					<value>1</value>
				</item>
				<item>
					<value>5</value>
				</item>
				<item>
					<value>4</value>
				</item>
			</list>
		</inputNode>
		<inputNode name="stringList">
			<list>
				<item>
					<value>a</value>
				</item>
				<item>
					<value>8</value>
				</item>
				<item>
					<value>Aa</value>
				</item>
				<item>
					<value>A</value>
				</item>
				<item>
					<value>10</value>
				</item>
				<item>
					<value>9</value>
				</item>
			</list>
		</inputNode>
		<inputNode name="tableB">
			<list>
				<item>
					<component name="col1">
						<value>16</value>
					</component>
					<component name="col2">
						<value>4</value>
					</component>
					<component name="col3">
						<value>25</value>
					</component>
					<component name="col4">
						<value>1</value>
					</component>
				</item>
				<item>
					<component name="col1">
						<value>16</value>
					</component>
					<component name="col2">
						<value>43</value>
					</component>
					<component name="col3">
						<value>2</value>
					</component>
					<component name="col4">
						<value>10</value>
					</component>
				</item>
				<item>
					<component name="col1">
						<value>1</value>
					</component>
					<component name="col2">
						<value>0</value>
					</component>
					<component name="col3">
						<value>1</value>
					</component>
					<component name="col4">
						<value>1</value>
					</component>
				</item>
			</list>
		</inputNode>
		<resultNode name="sort1" type="decision">
			<expected>
				<list>
					<item>
						<value>5</value>
					</item>
					<item>
						<value>4</value>
					</item>
					<item>
						<value>3</value>
					</item>
					<item>
						<value>1</value>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="sort2" type="decision">
			<expected>
				<list>
					<item>
						<component name="col1">
							<value>1</value>
						</component>
						<component name="col2">
							<value>0</value>
						</component>
						<component name="col3">
							<value>1</value>
						</component>
						<component name="col4">
							<value>1</value>
						</component>
					</item>
					<item>
						<component name="col1">
							<value>16</value>
						</component>
						<component name="col2">
							<value>4</value>
						</component>
						<component name="col3">
							<value>25</value>
						</component>
						<component name="col4">
							<value>1</value>
						</component>
					</item>
					<item>
						<component name="col1">
							<value>16</value>
						</component>
						<component name="col2">
							<value>43</value>
						</component>
						<component name="col3">
							<value>2</value>
						</component>
						<component name="col4">
							<value>10</value>
						</component>
					</item>
				</list>
			</expected>
		</resultNode>
		<resultNode name="sort3" type="decision">
			<expected>
				<list>
					<item>
						<value>10</value>
					</item>
					<item>
						<value>8</value>
					</item>
					<item>
						<value>9</value>
					</item>
					<item>
						<value>A</value>
					</item>
					<item>
						<value>Aa</value>
					</item>
					<item>
						<value>a</value>
					</item>
				</list>
			</expected>
		</resultNode>
	</testCase>
</testCases>

=== dmn-tck/tck/runners/dmn-tck-marshaller/src/test/resources/compliance-level-2/0002-input-data-number/0002-input-data-number-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0002-input-data-number.dmn</modelName>
	<labels>
		<label>base</label>
		<label>simple type</label>
	</labels>
	<testCase id="001"> 
		<description>Testing valid input</description>
		<inputNode name="Monthly Salary">
			<value>10000</value>
		</inputNode>
		<resultNode name="Yearly Salary" type="decision">
			<computed>
				<value>120000</value>
			</computed>
		</resultNode>
	</testCase>
	<testCase id="002">
		<description>Testing invalid input</description>
		<!-- is the following number type override valid? -->
		<inputNode name="Monthly Salary" type="feel:string">
			<value>foo</value>
		</inputNode>
		<!-- how do we test for invalid result? -->
	</testCase>
</testCases>

=== dmn-tck/tck/TestCases/compliance-level-2/0102-feel-constants/0102-feel-constants-test-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.omg.org/spec/DMN/20160719/testcase ../../testCases.xsd">
	<modelName>0102-feel-constants.dmn</modelName>
	<labels>
	    <label>Compliance Level 2</label>
		<label>Literal Expression</label>
	    <label>FEEL Constants</label>
	    <label>Data Type: String</label>
	</labels>
	<testCase id="001"> 
		<description>Tests FEEL string constants</description>
		<resultNode name="Decision1" type="decision">
			<expected>
				<value>foo bar</value>
			</expected>
		</resultNode>
	    <resultNode name="Decision2" type="decision">
	        <expected>
	            <value>šomeÚnicodeŠtriňg</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision3" type="decision">
	        <expected>
	            <value>横綱</value>
	        </expected>
	    </resultNode>
	    <resultNode name="Decision4" type="decision">
	        <expected>
	            <value>thisIsSomeLongStringThatMustBeProcessedSoHopefullyThisTestPassWithItAndIMustWriteSomethingMoreSoItIsLongerAndLongerAndLongerAndLongerAndLongerTillItIsReallyLong</value>
	        </expected>
	    </resultNode>
	</testCase>
</testCases>
